import { describe, expect, it } from "bun:test";
import { InMemoryMediaStorage } from "../../../shared/storage/media-storage.in-memory";
import { type GeminiImageClient, GeminiImageGenerator } from "./image-generator.gemini";

describe("GeminiImageGenerator", () => {
  it("stores the generated bytes and returns an ImageContent pointing at the stored url", async () => {
    const base64 = Buffer.from("png-bytes").toString("base64");
    const calls: { model: string; contents: string }[] = [];
    const client: GeminiImageClient = {
      models: {
        generateContent: async (args) => {
          calls.push({ model: args.model, contents: args.contents });
          return {
            candidates: [
              { content: { parts: [{ inlineData: { data: base64, mimeType: "image/png" } }] } },
            ],
          };
        },
      },
    };
    const storage = new InMemoryMediaStorage();

    const image = await new GeminiImageGenerator(client, storage, "gemini-2.5-flash-image").generate(
      "a cat",
    );

    expect(calls[0]?.contents).toBe("a cat");
    expect(image.uri).toBe("memory://0");
    expect(image.mimeType).toBe("image/png");
    expect(Buffer.from(storage.stored[0]!.data).toString()).toBe("png-bytes");
  });
});
